import Head from "next/head";

export default function Home() {
  return (
    <div className="bg-black flex flex-col items-center justify-center min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-6xl text-green-500">Hello World</h1>
    </div>
  );
}
